name: proroot_pc
description: Rootless native-performance Linux desktop for Android.
publish_to: "none"
version: 0.2.0-dev.6+47

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
